### ISSUE TITLE
Documentation website not working 

### ISSUE THREAD

**Issue by sw1pr0g** [moveit/moveit_task_constructor#568]
When i trying to access documentation website - https://ros-planning.github.io/moveit_task_constructor it drops a 404 Not Found Error. A few weeks ago all works. 
![Screenshot 2024-05-13 at 11 33 35 AM](https://github.com/moveit/moveit_task_constructor/assets/80714499/625c6c8d-ee37-4fbc-918a-b6425e10eba6)

**Comment by rhaschke** [comment]
All MoveIt repositories were migrated to a new github organization `moveit`. Where did you find the broken link?

**Comment by sw1pr0g** [comment]
in links of repository
![Screenshot 2024-05-13 at 1 25 58 PM](https://github.com/moveit/moveit_task_constructor/assets/80714499/a121ee4b-2cb2-4ec6-8812-d26d638fc291)

**Comment by sw1pr0g** [comment]
Thank you.
