### ISSUE TITLE
Grasp generator issue 

### ISSUE THREAD

**Issue by ron007d** [moveit/moveit_task_constructor#572]
Hi all I have been trying to understand the grasp generator.
Trying to grasp a box using # finger gripper but getting this grasp generations :point_down: 

![Screenshot from 2024-05-22 16-48-09](https://github.com/moveit/moveit_task_constructor/assets/78581592/e8800acc-49ed-45d7-9c18-da7b78f88353)

where I want this grasp generation to get generated and executed :point_down:  , Some time its generated successfully and working but sometime its generating :point_up: this and executing. for which its not able to grab the object correctly in simulation.

![Screenshot from 2024-05-22 16-48-02](https://github.com/moveit/moveit_task_constructor/assets/78581592/d2373710-eb5b-4648-8524-630daf94b5cc)

> python code used for generating grasps
```python
    grasp_generator = stages.GenerateGraspPose("Generate Grasp Pose")
    grasp_generator.angle_delta = 1.5708
    grasp_generator.pregrasp = "open"
    grasp_generator.grasp = "close"
    grasp_generator.setMonitoredStage(task["current"]) 
    grasp_generator.object = object_name
```
Thanks

**Comment by rhaschke** [comment]
The `GenerateGraspPose` stage just creates Cartesian poses around the object's frame by rotating about the z-axis by default. Additionally some properties, like pregrasp and grasp posture for fingers are set, which can be used by _neighbouring_ stages to actually actuate the fingers.

**Comment by ron007d** [comment]
Thanks @rhaschke  I will check it out, first I thought it was issue with the object size but then its showed the same for bigger object, 

there was a python doc for moveit task constructor, but it was showing 404,  can you help me with the link for that page ?

**Comment by rhaschke** [comment]
The docs are available here: https://moveit.github.io/moveit_task_constructor/api.html

**Comment by ron007d** [comment]
I figured out that jupyter notebook don't have the sourced directory thus **it was not able to get the model info**, now its fetching error on certain grasp,
- added gripper group name in grasp
- added object name in grasp
- added `source ...devel.bash` info the jupyter server.

![image](https://github.com/moveit/moveit_task_constructor/assets/78581592/c4de7510-90c3-4275-862b-e48ec91348ca)
